# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install coverage
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Unit Tests and generate coverage report
        run: |
          cd src
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html
      - name: Archive code coverage html report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: src/htmlcov

  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yangruu/cicd:latest